a = open("demo.txt","a")
a.write(" appended content ")
a.close()
b = open("demo.txt")
print(b.read())
b.close()
c = open("demo.txt","w")
c.write(" overwritten content ")
c.close()
d = open("demo.txt")
print(d.read())
d.close()